### ISSUE TITLE
Add a new "Home" menu item to navigation bar

### ISSUE THREAD

**Issue by engineSound** [hydroshare/hs_pages#10]
## Release
This is needed for release 1.23. @Lizabrazil 

## What's new
We are adding a new page to hydroshare. 

## Behavior change
When a user login, a new home page is displayed. The new home page is different than what is currently at www.hydroshare.org. 

![2019-04-22_15-15-52](https://user-images.githubusercontent.com/35352595/56520080-929b2000-6511-11e9-843d-51f1105fce54.png)

## Requested change
The "home" points to "/dashboard/". It is similar to "My Resources"

**Comment by Lizabrazil** [comment]
@engineSound The URL is /home ....
Not .     /dashboard correct?

**Comment by horsburgh** [comment]
Are these the same page? I would expect “home” to go to the hydroshare home page and “dashboar to go to the dashboard.

**Comment by Lizabrazil** [comment]
We looked at how other websites do this. 
Landing page is associated with HydroShare logo top left= hydroshare.org 
Dashboard is HOME and is hydroshare.org/home

Other websites have the user sign in, use the dashboard as their starting point with /home and only when they sign out they are brought back to landing page. This makes it seem like they have entered into the HS ecosystem and now have access to all parts of it. When we do the HIS integration, this will work together well, as the user will login into their CUAHSI Data Services account from the landing page and have access to all components.

**Comment by horsburgh** [comment]
I guess I’m missing the distinction between HydroShare.org and “home”. The dashboard is the dashboard and the homepage is the homepage. My experience with other sites has been opposite of yours I guess.

**Comment by Lizabrazil** [comment]
![image](https://user-images.githubusercontent.com/13852599/56531080-68515e80-6521-11e9-8b45-49bb9a3bf6c9.png)
 Here's one example, Figshare uses the user's dashboard with the URL home in it. 
I was trying to find examples of Dashboards with Navigation being "Dashboard" and couldn't. Do you have examples? I am still open to changing it but at this point we are trying to push this out the door.

**Comment by horsburgh** [comment]
@Lizabrazil - We have created functionality that we are calling "Dashboard", so why would we create a link to it called "Home"? I think people look less at the URL pattern than they do at the main navigational links of the site, but I also don't see why we wouldn't make those consistent - the page is called dashboard, the link is called dashboard, and the URL is /dashboard/.

For what it's worth - I've always found the navigation of Figshare confusing. Figshare never uses the word "Dashboard". They do use "My Data" at the top of the page, but then they have "Projects", "Collections", and "Activity" that don't appear in their main navigation. These aren't the same as "My data", but I can't get to them without going to "My Data" first. I'm not sure we should use them as an example.

**Comment by Lizabrazil** [comment]
@horsburgh I went back and forth with this a lot but ultimately when i looked at what is on the dashboard for this iteration (easy way to start performing tasks with resources and apps) and what we have planned to incorporate in future iterations (social elements, newsfeed elements, quick links/short cut customization, etc.) it felt like more of a Homepage rather than a Dashboard. On the other hand, I know we are also planning to add a couple metrics for reporting on the dashboard, and so that made me want to call it Dashboard. Ultimately, I saw that we are doing more homepage functionality versus data statistics and that is what pushed me to call it "home. " I really did go back and forth with this a lot, should we discuss on the phone? Also, if we call it home, the URL would be hydroshare.org/home

**Comment by engineSound** [comment]
Calling it home is future looking to accomondate the vision Jeff laid out a few years ago. Calling dashboard is a bit narrow for what we are aiming for.

**Comment by engineSound** [comment]
> @engineSound The URL is /home ....
> Not . /dashboard correct?

it is /home.

**Comment by engineSound** [comment]
> I think people look less at the URL pattern than they do at the main navigational links of the site

I have the same observation.

**Comment by hyi** [comment]
Just chime in with a minor point: why don't we use hydroshare.org as the home URL rather than hydroshare.org/home given that usually the main site is the home page?

**Comment by engineSound** [comment]
There is plan by ear to handle the current hydroshare.org home page sometime down the road.

Looking at the situation we are facing.  The current home page and dashboard co-exist. It is an ambiguity where the url point.

**Comment by engineSound** [comment]
The latest dashboard/home is available at https://dev-hs-5.cuahsi.org

**Comment by cbcunc** [comment]
Including email exchange (sans email addresses) for documentation. Based on it, I'm merging #12 into develop. If you change your minds later, it can be fixed. I won't merge to master until the dashboard is ready. For now it will be deployed to pages.hydroshare.org only and not to help.hydroshare.org.

```
On 4/23/19, 10:20 AM, "Hongzhen Zhang"  wrote:
 
Chris,
 
My bad. I forgot the dashboard has changed to home. It should be www.hydroshare.org/home. I actually have been in a confused state by my own stake.
 
Thanks,
Hongzhen
 
 
From: Liza Brazil  Date: Tuesday, April 23, 2019 at 7:49 AM To: "Calloway, Chris"  Cc: Hongzhen Zhang  Subject: Re: Help.hydroshare.org changes
 
Sorry Chris, we are now circling back on some phrasing. We will get to this asap today.
   
On Apr 22, 2019, at 5:00 PM, Calloway, Chris  wrote:
 
Liza,
 
I changed /dashboard/ to /home/. Will you please verify this is what you want by looking at:
 
https://pages.hydroshare.org/
 
and then submitting an approval by review to:
 
https://github.com/hydroshare/hs_pages/pull/12
 
Hongzhen, would you pleaset tell me that you agree with Liza that the URL should be /home/ via an additional comment on the PR?
 
-- 
Sincerely,
 
Chris Calloway
Applications Analyst
University of North Carolina
Renaissance Computing Institute

 
 
On 4/22/19, 4:51 PM, "Calloway, Chris"  wrote:
 
Yes, this will not be deployed to help.hydroshare.org until the dashboard is ready.
 
I can add another commit to have it point to /home/ instead of /dashboard/. The issue that was filed asked for /dashboard/.
 
Note that www.hydroshare.org/home/ doesn’t exist yet, either.
 
-- 
Sincerely,
 
Chris Calloway
Applications Analyst
University of North Carolina
Renaissance Computing Institute

 
 
On 4/22/19, 4:40 PM, "Liza Brazil"  wrote:
 
Hi Chis, 
 
Thanks for your help on this. I clicked HOME on the nav it brought me to page doesn’t exist, I noticed you used the URL https://www.hydroshare.org/dashboard/ which should be https://www.hydroshare.org/home/
 
Best,
Liza
     
On Apr 22, 2019, at 4:14 PM, Calloway, Chris  wrote:
 
I requested your review on this pull request:
 
https://github.com/hydroshare/hs_pages/pull/12
 
To help your review, I already posted the change to the help staging site (pages.hydroshare.org) so you can view it and see if it is what you want:
 
https://pages.hydroshare.org/
 
-- 
Sincerely,
 
Chris Calloway
Applications Analyst
University of North Carolina
Renaissance Computing Institute

 
 
On 4/22/19, 3:28 PM, "Hongzhen Zhang"  wrote:
 
Chris,
 
Correct. The page doesn’t exist on www.hydroshare.org yet. It will exist in release 1.23 which is at least a couple of weeks from today.
Let’s add product manager Liza in the email thread.
 
Liza,
 
I think the procedure is www.hydroshare.org goes on product, then help.hydroshare.org get updated to reflect the production.
 
-Hongzhen
 
From: "Calloway, Chris"  Date: Monday, April 22, 2019 at 3:19 PM To: Hongzhen Zhang  Subject: Re: Help.hydroshare.org changes
 
So, you want a home link on help.hydroshare.org to switch sites to www.hydroshare.org and a page that doesn’t exist yet?
 
-- 
Sincerely,
 
Chris Calloway
Applications Analyst
University of North Carolina
Renaissance Computing Institute

 
 
On 4/22/19, 3:10 PM, "Hongzhen Zhang"  wrote:
 
Hi Chris,
 
Clicking “home” brings to https://www.hydroshare.org/dashboard
 
Hongzhen Zhang
Software Engineer, CUAHSI
www.cuahsi.org
Sign up for CUAHSI news here!
 
 
From: "Calloway, Chris"  Date: Monday, April 22, 2019 at 2:36 PM To: Hongzhen Zhang  Subject: Re: Help.hydroshare.org changes
 
And clicking on “home” would take you to help.hydroshare.org’s front page?
 
-- 
Sincerely,
 
Chris Calloway
Applications Analyst
University of North Carolina
Renaissance Computing Institute

 
 
On 4/22/19, 1:33 PM, "Hongzhen Zhang"  wrote:
 
Hi Chris,
 
Thank you for proactively following up with my request.
 
I wanted to add a new item “Home” in front of the "My Resource" to the navigation bar.
 
 
<image001.png>
 
 
Thank you! 
Hongzhen
On April 22, 2019 at 12:59:29 PM, Calloway, Chris  wrote:
Hongzhen,
 
What very specific change do you want to make to help.hydroshare.org? I understand you want something added to navigation. But what and where?
 
-- 
Sincerely,
 
Chris Calloway
Applications Analyst
University of North Carolina
Renaissance Computing Institute
```

**Comment by Lizabrazil** [comment]
@horsburgh @hyi 
Hydroshare.org is the landing page. Hydroshare.org/home is the user's homepage, it is where they can easily access resources that they were most recently working on/viewing/finding. As we build out the Home (dashboard), we may add a newsfeed and social functionality and other "home" like functionality. Think of Facebook. You go to Facebook and if you are not logged in then you see their landing page that says what Facebook is and to login. Then you login  and you see your Home. This is your jumping off point, information that is relevant to your activity.

**Comment by hyi** [comment]
@Lizabrazil Thanks for the clarification - I think I got your point now regarding whether to call it user's homepage or user's dashboard. I think my confusion came from terminology for 'homepage.' In my mind, 'homepage' refers to the landing page for the site that introduces what HydroShare is and allow users to sign up, sign in, etc. After the user signs in, the user can be taken to his or her dashboard with customized page tailored to the user. I think dashboard would work better than home page to avoid confusion here.

**Comment by Lizabrazil** [comment]
@hyi Best practice is to bring the user to their home after login. Websites usually do not bring a user directly to a dashboard after login.

**Comment by horsburgh** [comment]
@Lizabrazil - we are talking about the same thing, and now we are just discussing semantics. I think we can avoid the potential confusion of having a "homepage" AND a "home" page by just calling the new page "dashboard". 

This article is instructive, but doesn't clear it up entirely: 

https://en.wikipedia.org/wiki/Home_page 

> A home page is generally the main page a visitor navigating to a website from a web search engine will see, and it may also serve as a landing page to attract visitors.

http://www.hydroshare.org serves this purpose. It is HydroShare's homepage, but yes, according to this article it is also a landing page.

> Once they are logged in, the home page may be redirected to their profile page. This may in turn be referred to as the "personal home page."

We aren't redirecting to HydroShare's profile page, we have chosen to redirect to a page with dynamic content intended to engage the user. We have been calling that page "dashboard" for months now. In other words, the dashboard is the "personal home page." 

I don't think there's a definitive best practice out there for this. We've seen it both ways. We just need to decide what we want to do. I vote for calling the new page "dashboard".

**Comment by martinseul** [comment]
As there is not definitive rule for the need for a home navigation item many websites still use it. The term dashboard is mostly used in applications that track metrics and help admins run their systems which does not really apply here. People are used to the term home as way a to get back to where they started. We used the term "Dashboard" internally but the userbase does not know what we mean with it and we should be careful to introduce a new term we have to explain. I think we should go with "Home" for now, use heap to instrument it and see how people use it. If people are not using the button as we expect we can consider removing the item and rely on the HS icon or renaming it.

**Comment by dtarb** [comment]
Has this discussion of dashboard versus home looked at how this would work holistically.  Do we have a separate menu item at the top, or does the HydroShare logo serve as the menu item.  We previously designed the page heirarchy in 
https://docs.google.com/drawings/d/1WBGON5o7zDxSWaNytCMkIV1ewfSCQ0ccqXIz0w3ZOs0/edit

With the new pages being added, I think there is a need to look at the plan holistically, and update this diagram.

Also, there is a need to look at the Olin report suggestions about Dashboard.
