### ISSUE TITLE
Fix deployment script problems

### ISSUE THREAD

**Issue by cbcunc** [hydroshare/hs_pages#13]
1. pmctl start_nginx does not start nginx container before trying to modify nginx container.
1. pmctl loadmedia_pagemill attemps to create static/ in pagemill/pagemill instead of pagemill/
1. pmctl loadmedia_pagemill attempts to create pagemill/static after web containers starts and is owned by root
1. pmctl loadmedia_pagemill does not create pagemill/static/media prior to starting root owned web container
1. Dockerfile needs to support postgresql 9.6 (9.4 no longer in stretch repo)
1. docker-compose.yaml needs to support postgresql 9.6 container
1. Bump version in footer

**Comment by devincowan** [comment]
closing as deployment no longer uses pmctl
